# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days'
description:      'GAP developer meetings'
url:              http://gapdays.de
baseurl:          ''
