# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days'
description:      'GAP developer meetings'
url:              https://www.gapdays.de
baseurl:          ''

exclude: [ "LICENSE.hyde.md", "README.hyde.md" ]
